name: SonarCloud

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.2
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=mohitshukla
            -Dsonar.projectKey=MohitShukla_basis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Ensure this secret is defined in your repository
      - name: Check Quality Gate
        run: |
          curl -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MohitShukla_basis" > quality_gate.json
          if [ "$(jq -r '.projectStatus.status' quality_gate.json)" != "OK" ]; then
            echo "Quality Gate failed!"
            exit 1
